import das bibliotecas

In [ ]:
import pandas as pd #tratamento de DF
import numpy as np #calculos
import plotly.express as px #Criação de gráficos dinâmicos
import plotly.graph_objects as go #criação de concatenizaçaõ de gráficos
from sklearn.preprocessing import StandardScaler #realizar a padronização9 de dados
from sklearn.cluster import KMeans

#Analisando Base de Dados

Visualizar tabela

In [ ]:
base_iris = pd.read_csv("Iris.csv", sep =',')

In [ ]:
base_iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Renomae Colunas

In [ ]:
base_iris = base_iris.rename(columns={
    'id':'id',
    'SepalLengthCm':'sepal_lenght',
    'SepalWidthCm':'sepal_width',
    'PetalLengthCm':'pental_lenght',
    'PetalWidthCm':'pental_width',
    'Sepecies':'class'
})

In [ ]:
base_iris

Id  sepal_lenght  sepal_width  pental_lenght  pental_width  \
0      1           5.1          3.5            1.4           0.2   
1      2           4.9          3.0            1.4           0.2   
2      3           4.7          3.2            1.3           0.2   
3      4           4.6          3.1            1.5           0.2   
4      5           5.0          3.6            1.4           0.2   
..   ...           ...          ...            ...           ...   
145  146           6.7          3.0            5.2           2.3   
146  147           6.3          2.5            5.0           1.9   
147  148           6.5          3.0            5.2           2.0   
148  149           6.2          3.4            5.4           2.3   
149  150           5.9          3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

Deletando uma colnuna

In [ ]:
del base_iris['Id']

In [ ]:
base_iris

sepal_lenght  sepal_width  pental_lenght  pental_width         Species
0             5.1          3.5            1.4           0.2     Iris-setosa
1             4.9          3.0            1.4           0.2     Iris-setosa
2             4.7          3.2            1.3           0.2     Iris-setosa
3             4.6          3.1            1.5           0.2     Iris-setosa
4             5.0          3.6            1.4           0.2     Iris-setosa
..            ...          ...            ...           ...             ...
145           6.7          3.0            5.2           2.3  Iris-virginica
146           6.3          2.5            5.0           1.9  Iris-virginica
147           6.5          3.0            5.2           2.0  Iris-virginica
148           6.2          3.4            5.4           2.3  Iris-virginica
149           5.9          3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

Quantidade de Linhas e Colunas

In [ ]:
base_iris.shape

(150, 5)

Verificar as classes da flores - dados unicos

In [ ]:
base_iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

#Realizando Agrupamento das flores

Criando varável x com as colunas PetalLengthCm	PetalWidthCm
- pega os valores e transforma num array 

In [ ]:
x_petala = base_iris.iloc[:,[2,3]].values
x_petala[:10]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

#Normalização os dados

Como os dados estão em uma escala muito diferente, precisamos normalizar os dados colocando no mesmo padrão e na mesma escala.
Como o Kmeans realiza os calculos baseados na distancia, devemos padronizar os dados afim de que um atreibuto não seja considerado mais importante do que o outro.

In [ ]:
  normalizar_dados = StandardScaler() 
  x_petala = normalizar_dados.fit_transform(x_petala) #atribuir o fit_transform na variável
  x_petala[:10] #limitado a 10 registros

array([[-1.3412724 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.39813811, -1.31297673],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.17067529, -1.05003079],
       [-1.3412724 , -1.18150376],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.2844067 , -1.4444497 ]])

#Calculando o número de Cluster

Para calcular o número de cluster vamos utilizar o método do cotovelo
WCSS é a soma da distancia entre cada ponto e o centroide em um cluster

In [ ]:
wcss_petala = [] # criar lista vazia
for i in range(1,11): # inicia-se com 01 pois não existe 0 clusters
  kmeans_petala = KMeans(n_clusters=i, random_state=0) # Executa o Kmeans para todos os clusters e random_state = o para fixar e obter os mesmo resultados
  kmeans_petala.fit(x_petala) # realiza o treinamento
  wcss_petala.append(kmeans_petala.inertia_)

Visualizando os valores de wcss

In [ ]:
for i in range(len(wcss_petala)):
  print("Cluster:", i, "- valor do wcss", wcss_petala[i])

Cluster: 0 - valor do wcss 300.0000000000001
Cluster: 1 - valor do wcss 54.14584701344988
Cluster: 2 - valor do wcss 18.046983891906276
Cluster: 3 - valor do wcss 12.307440251261843
Cluster: 4 - valor do wcss 9.181131495513899
Cluster: 5 - valor do wcss 7.215096212730807
Cluster: 6 - valor do wcss 6.026593155951448
Cluster: 7 - valor do wcss 5.173315218915379
Cluster: 8 - valor do wcss 4.423975871969686
Cluster: 9 - valor do wcss 3.9139417830543204


# Criando gráfico para melhor visualização

In [ ]:
grafico_colovelo_petala = px.line( x=range(1,11), y=wcss_petala)
grafico_colovelo_petala.show()

In [ ]:
kmeans_petala = KMeans(n_clusters=3, random_state = 0)
label_cluster_petala = kmeans_petala.fit_predict(x_petala)

Verificando e classificação dos clusters

In [ ]:
label_cluster_petala

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

Chamando o centroides dos CLusters

In [ ]:
centroides_petala = kmeans_petala.cluster_centers_
centroides_petala 

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

# Grafico de agrupamento das caracterísicas do tamanho e comprimento das pétalas

In [ ]:
grafico_petala = px.scatter(x = x_petala[:,0], y = x_petala[:,1], color = label_cluster_petala)
grafico_centroide_petala = px.scatter(x = centroides_petala[:,0], y = centroides_petala[:,1], size = [7,7,7])
grafico_final_petala = go.Figure(data = grafico_petala.data + grafico_centroide_petala.data)
grafico_final_petala.show()

# Realizando o agrupamento com dados da sépala

In [ ]:
x_sepala = base_iris.iloc[:,[0,1]].values
x_sepala[:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

Calcular o WCSS

In [ ]:
wcss_sepala = [] # criar lista vazia
for i in range(1,11): # inicia-se com 01 pois não existe 0 clusters
  kmeans_sepala = KMeans(n_clusters=i, random_state=0) # Executa o Kmeans para todos os clusters e random_state = o para fixar e obter os mesmo resultados
  kmeans_sepala.fit(x_sepala) # realiza o treinamento
  wcss_sepala.append(kmeans_sepala.inertia_) # adicona na lista os valore de wcss

Visualizar os valores de wcss

In [ ]:
for i in range(len(wcss_sepala)):
  print("Cluster:", i, "- valor do wcss", wcss_sepala[i])

Cluster: 0 - valor do wcss 130.18093333333337
Cluster: 1 - valor do wcss 57.98240604207879
Cluster: 2 - valor do wcss 37.12370212765957
Cluster: 3 - valor do wcss 27.98254281735862
Cluster: 4 - valor do wcss 20.971913367009606
Cluster: 5 - valor do wcss 17.238695238095236
Cluster: 6 - valor do wcss 14.631909607059608
Cluster: 7 - valor do wcss 12.911711915446565
Cluster: 8 - valor do wcss 11.059663725936947
Cluster: 9 - valor do wcss 9.449454365079365


In [ ]:
grafico_colovelo = px.line( x=range(1,11), y=wcss_sepala)
grafico_colovelo.show()

Executando o algoritmo k-means

In [ ]:
kmeans_sepala = KMeans(n_clusters=3, random_state = 0)
label_cluster_sepala = kmeans_sepala.fit_predict(x_sepala)

Verificando a classificação dos clusters

In [ ]:
label_cluster_sepala

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [ ]:
centroides_sepala = kmeans_sepala.cluster_centers_
centroides_sepala 

array([[5.77358491, 2.69245283],
       [5.006     , 3.418     ],
       [6.81276596, 3.07446809]])

Gráfico de agrupaento das características do tamanho e comprimnto das sépalas

In [ ]:
grafico = px.scatter(x = x_sepala[:,0], y = x_sepala[:,1], color = label_cluster_sepala)
grafico_centroide = px.scatter(x = centroides_sepala[:,0], y = centroides_sepala[:,1], size = [7,7,7])
grafico_final= go.Figure(data = grafico.data + grafico_centroide.data)
grafico_final.show()

Gráfico de agrupamento das características do tamanho e comprimento das sépalas

In [ ]:
grafico_petala = px.scatter(x = x_petala[:,0], y = x_petala[:,1], color = label_cluster_petala)
grafico_centroide_petala = px.scatter(x = centroides_petala[:,0], y = centroides_petala[:,1], size = [7,7,7])
grafico_final_petala = go.Figure(data = grafico_petala.data + grafico_centroide_petala.data)
grafico_final_petala.show()